#!/bin/bash

if [ ! -d ${GITEA_HOME}/ssh ]; then
    mkdir -p ${GITEA_HOME}/ssh
fi

if [ ! -f ${GITEA_HOME}/ssh/ssh_host_ed25519_key ]; then
    echo "Generating ${GITEA_HOME}/ssh/ssh_host_ed25519_key..."
    ssh-keygen -t ed25519 -f ${GITEA_HOME}/ssh/ssh_host_ed25519_key -N "" > /dev/null
fi

if [ ! -f ${GITEA_HOME}/ssh/ssh_host_rsa_key ]; then
    echo "Generating ${GITEA_HOME}/ssh/ssh_host_rsa_key..."
    ssh-keygen -t rsa -b 2048 -f ${GITEA_HOME}/ssh/ssh_host_rsa_key -N "" > /dev/null
fi

if [ ! -f ${GITEA_HOME}/ssh/ssh_host_dsa_key ]; then
    echo "Generating ${GITEA_HOME}/ssh/ssh_host_dsa_key..."
    ssh-keygen -t dsa -f ${GITEA_HOME}/ssh/ssh_host_dsa_key -N "" > /dev/null
fi

if [ ! -f ${GITEA_HOME}/ssh/ssh_host_ecdsa_key ]; then
    echo "Generating ${GITEA_HOME}/ssh/ssh_host_ecdsa_key..."
    ssh-keygen -t ecdsa -b 256 -f ${GITEA_HOME}/ssh/ssh_host_ecdsa_key -N "" > /dev/null
fi

if [ -d /etc/ssh ]; then
    SSH_PORT=${SSH_PORT:-"22"} \
    SSH_LISTEN_PORT=${SSH_LISTEN_PORT:-"${SSH_PORT}"} \
    envsubst < /etc/templates/sshd_config > /etc/ssh/sshd_config

    chmod 0644 /etc/ssh/sshd_config
fi

chown root:root ${GITEA_HOME}/ssh/*
chmod 0700 ${GITEA_HOME}/ssh
chmod 0600 ${GITEA_HOME}/ssh/*
